### ISSUE TITLE
Incorrect hostname shown on canvas

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1297]
A simple Docker compose file:
```
version: '2'
services:
  ubuntu:
    image: ubuntu
    hostname: ubuntu
    domainname: weave.local.
    dns_search: weave.local.
    network_mode: weave
    dns: 172.17.0.1
    tty: true
    command: sh
```
is used to launch 5 containers on 4 Swarm hosts:
```
docker-compose up -d
docker-compose scale=5
```
<img width="1234" alt="scope-hostname-mismatch" src="https://cloud.githubusercontent.com/assets/303151/14496789/4c914030-018c-11e6-96ef-eebfc21efac3.png">

The hostname for each container is shown on the canvas as 'swarm-node-2', but the hostname is correctly stated in the detail panel header.
