### ISSUE TITLE
Weave Scope should optionally leverage annotations to connect containers and services

### ISSUE THREAD

**Issue by kelseyhightower** [weaveworks/scope#1413]
Currently Weave Scope relies solely on observing network traffic to "draw" connections between containers and external clients. As a user I would also like to see the desired state as defined by me or the cluster manager. This feature should be entirely optional, but when enabled, Scope should use a new connector (dotted line) between containers and services that should be connected and another connector (solid line) to show active connections.

In the case of Kubernetes annotations can be leveraged like this:

#### Pods

```
# backend
apiVersion: v1
kind: Pod
metadata:
  name: backend
  annotations:
    weavescope/service-provided: backend
    weavescope/services-consumed: mysql,redis
```

```
# frontend
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  annotations:
    weavescope/service-provided: frontend
    weavescope/services-consumed: backend
```

#### Services

When it comes to services, Weave Scope should utilize the label queries provided on the service objects to render the desired state connections.
