### ISSUE TITLE
Scope (Cloud version) + K8S: Inconsistent topology

### ISSUE THREAD

**Issue by rshriram** [weaveworks/scope#1553]
Hi
 When using Scope (the cloud version) with Kubernetes, the application topology that was being rendered seemed to miss a lot of information regarding connectivity between nodes. In addition,

- The scope UI does not show the communication between containers in the same pod
  If I filter the display by "Containers", the topology shows a set of communicating containers in "different" pods. The other containers in the above pods are shown as isolated nodes with no communication into or out of the container.

- The scope UI does not have a way to aggregate the topology based on pod to pod communication either.

Any idea how to set this up in the right way?

I am not sure if my setup is right. I followed the documentation. Here is the part corresponding to the probe config:
```yaml
  - metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-probe
      name: weavescope-probe
    apiVersion: extensions/v1beta1
    kind: DaemonSet
    spec:
      template:
        metadata:
          labels:
            app: weavescope
            weavescope-component: weavescope-probe
        spec:
          hostPID: true
          hostNetwork: true
          containers:
            - name: weavescope-probe
              image: 'weaveworks/scope:0.15.0'
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - '--service-token=DUMMY'
#                - '$(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)'
              securityContext:
                privileged: true
              resources:
                limits:
                  cpu: 50m
              volumeMounts:
                - name: docker-sock
                  mountPath: /var/run/docker.sock
          volumes:
            - name: docker-sock
              hostPath:
                path: /var/run/docker.sock
```

However, I also found several errors in the logs:
```
vagrant@host:~/sandbox/examples$ kubectl logs weavescope-probe-q1kjh
<probe> INFO: 2016/06/06 23:42:50.490590 probe starting, version 0.15.0, ID 540a6cf3578a050d
<probe> INFO: 2016/06/06 23:42:50.490703 command line: [scope-probe --mode probe --no-app --probe.docker.bridge=docker0 --probe.docker=true --probe.kubernetes=true --service-token=DUMMY scope.weave.works:443]
<probe> INFO: 2016/06/06 23:42:50.490802 publishing to: scope.weave.works:443
<probe> INFO: 2016/06/06 23:42:53.086332 docker container: collecting stats for 34e25e4e1411c347c7db63c2664dbe6266ec507f679bd824b846bd6f3c934d51
<probe> INFO: 2016/06/06 23:42:53.785939 Deployments and ReplicaSets are not supported by this Kubernetes version
<probe> ERRO: 2016/06/06 23:42:53.786385 plugins: problem loading: no such file or directory
<probe> ERRO: 2016/06/06 23:42:53.786794 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
<probe> ERRO: 2016/06/06 23:42:53.791384 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.ReplicationController: the server has asked for the client to provide credentials (get replicationcontrollers)
<probe> ERRO: 2016/06/06 23:42:54.286123 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
<probe> ERRO: 2016/06/06 23:42:54.587434 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
<probe> INFO: 2016/06/06 23:42:54.589418 docker container: collecting stats for 564360c7c7467265d0cfed68473a205aa756dde44482de02adbe5550e93b890b
<probe> INFO: 2016/06/06 23:42:56.987181 Publish loop for 52.5.255.40:443 starting
<probe> WARN: 2016/06/06 23:42:59.586111 Endpoint reporter took longer than 1s
<probe> ERRO: 2016/06/06 23:43:00.491598 'weave ps' cmd failed: exit status 1
<probe> ERRO: 2016/06/06 23:43:00.589961 Error collecting weave info, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
```
