### ISSUE TITLE
probe's procspy does not report netcat's half-duplex long-lived connections

### ISSUE THREAD

**Issue by alban** [weaveworks/scope#1972]
The reproducer below creates a container in Kubernetes and it creates two long-lived processes:
- A listening process "nc"
- A connecting process "nc"

The connection and processes are long-lived. But still, the connection is not displayed in the Scope UI. When I inspect /proc manually, I see that the 2 processes exist and are connected to each other.

I am using a Fedora based image to reproduce this bug because I couldn't get "nc" to work correctly in busybox (in busybox, "nc" is a built-in of the shell, and it does not seem to fork a new process when invoked).

```
apiVersion: v1
kind: Pod
metadata:
  name: connectlo
  labels:
    name: connectlo
spec:
  containers:
  - name: connectlo
    image: albanc/toolbox
    args:
      - '/bin/sh'
      - '-c'
      - "MYIP=$(ip addr show eth0 | grep \"inet\\b\" | awk '{print $2}' | cut -d/ -f1) ; echo MYIP=$MYIP ; (/bin/nc -l --keep-open -p 8081 & ) ; sleep 1 ; echo CLIENT ; (echo Hello ; sleep 1000 ; echo 'Bye' ) | /bin/nc $MYIP 8081"
```

I also tried with 127.0.0.1 instead of the eth0's IP address, but it also does not work.

This issue was discussed on https://github.com/weaveworks/scope/pull/1967#issuecomment-257624674. See also https://github.com/weaveworks/scope/pull/1780.

I have not checked the json report.

/cc @2opremio

**Comment by 2opremio** [comment]
> When I inspect /proc manually, I see that the 2 processes exist and are connected to each other.

How did you verify that they are connected?

**Comment by 2opremio** [comment]
I have reproduced the lack of reflexive edge with a similar, simpler test: 

```
$ docker run -ti --name one --rm alpine sh -c 'nc -l -p 1122 & sleep 2; nc 127.0.0.1 1122'
testing echo
testing echo
[...]
```

Interestingly, the sockets get in CLOSE_WAIT/FIN_WAIT_2 state instead of ESTABLISHED:

```
$ docker exec -ti one ash
/ # netstat -nt
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.1:34336         127.0.0.1:1122          CLOSE_WAIT  
tcp        0      0 ::ffff:127.0.0.1:1122   ::ffff:127.0.0.1:34336  FIN_WAIT2   
/ # 
```


Our `/proc` walker [only considers ESTABLISHED connections](https://github.com/weaveworks/scope/blob/53bc710c4e912b0f27da55e11c0749024f624dcf/probe/endpoint/procspy/spy_linux.go#L64) causing the connections to be filtered out.

Removing the filter causes the expected reflexive edge to appear.

I am not sure we should simply remove the filter (I need to think about the performance and correctness implications) but in the meantime, @alban would you mind confirming whether the sockets get in that state?

**Comment by 2opremio** [comment]
@alban I have tried to reproduce with your kubernetes example and I simply get:

```
MYIP=
CLIENT
Ncat: You must specify a host to connect to. QUITTING.
```

**Comment by alban** [comment]
> @alban would you mind inspecting the sockets' state in your Kubernetes example?

You're right:
```
# nsenter -t 12345 -n  netstat -ntp|grep nc
tcp        0      0 172.17.0.22:40080       172.17.0.22:8081        CLOSE_WAIT  12572/nc
tcp        0      0 172.17.0.22:8081        172.17.0.22:40080       FIN_WAIT2   12345/nc
```

The server is in `FIN_WAIT2` because it has done a `shutdown(SHUT_WR)` because it does not need to send data (it only needs to receive data). The client is in `CLOSE_WAIT` because it has receive the `FIN from the server`.

If I change the `nc` command to actually send & receive data, then it is `ESTABLISHED` (notice the `nc -e /bin/cat` used to force `nc` to keep the connection in duplex mode):
```
apiVersion: v1
kind: Pod
metadata:
  name: connectlo
  labels:
    name: connectlo
spec:
  containers:
  - name: connectlo
    image: albanc/toolbox
    args:
      - '/bin/sh'
      - '-c'
      - "MYIP=$(ip addr show eth0 | grep \"inet\\b\" | awk '{print $2}' | cut -d/ -f1) ; echo MYIP=$MYIP ; (/bin/nc -l --keep-open -e /bin/cat -p 8081 & ) ; sleep 1 ; echo CLIENT ; (echo Hello ; sleep 1000 ; echo 'Bye' ) | /bin/nc $MYIP 8081"
```

In that case (`nc` keeping the connection in duplex mode), the connection is `ESTABLISHED`:
```
# nsenter -t 20781 -n  netstat -ntp|grep nc
tcp        0      0 172.17.0.22:8081        172.17.0.22:43950       ESTABLISHED 21012/nc
tcp        0      0 172.17.0.22:43950       172.17.0.22:8081        ESTABLISHED 20988/nc
```

And the reflexive edge appears correctly in Scope.
