### ISSUE TITLE
probe: endpoints "copy_of" logic for NAT does not work on services served by multiple pods

### ISSUE THREAD

**Issue by alban** [weaveworks/scope#2129]
While trying to understand an issue with NAT on the ebpf branch, we noticed this bug reproduced on master.

The Kubernetes yaml file below starts:
- 2 server pods (myserver1 and myserver2)
- 1 Kubernetes service that load balance the traffic to the two servers
- 2 clients pods (myclient1 and myclient2). Each creates one connection to the Kubernetes service. 

When I tried this, each client got connected to a different server (the load balancer did its job correctly):

```
$ sudo docker run --privileged --net=host --pid=host --rm albanc/toolbox conntrack -L -p tcp|grep 10.0.0.88|grep ESTABLISHED
conntrack v1.4.3 (conntrack-tools): 320 flow entries have been shown.
tcp      6 84754 ESTABLISHED src=172.17.0.21 dst=10.0.0.88 sport=34442 dport=80 src=172.17.0.18 dst=172.17.0.21 sport=80 dport=34442 [ASSURED] mark=0 use=1
tcp      6 84751 ESTABLISHED src=172.17.0.20 dst=10.0.0.88 sport=56974 dport=80 src=172.17.0.19 dst=172.17.0.20 sport=80 dport=56974 [ASSURED] mark=0 use=1
```

So far so good.

Howevever, Scope does not show this correctly: it is oscillating between the following two "N" graphes:

![image](https://cloud.githubusercontent.com/assets/27575/21937754/bec9c776-d9b8-11e6-96a1-927cd0689dba.png)

![image](https://cloud.githubusercontent.com/assets/27575/21938229/bc17ac62-d9ba-11e6-9873-872bdfc1a666.png)

I believe this is cause by the "copy_of" node in the endpoints topology: it has the wrong direction. ";172.17.0.19;80" should be a copy of ";10.0.0.88;80" instead of the other way around. Since the node with id ";10.0.0.88;80" needs to be unique, it cannot be a "copy of" both myserver1 and myserver2

```
         ";10.0.0.88;80" : {
            "topology" : "endpoint",
            "latestControls" : {},
            "controls" : {},
            "sets" : {},
            "adjacency" : null,
            "id" : ";10.0.0.88;80",
            "latest" : {
               "copy_of" : {
                  "value" : ";172.17.0.19;80",
                  "timestamp" : "2017-01-13T16:38:00.543177256Z"
               },
               "pid" : {
                  "timestamp" : "2017-01-13T16:37:50.566120599Z",
                  "value" : "20039"
               },
               "conntracked" : {
                  "value" : "true",
                  "timestamp" : "2017-01-13T16:38:00.519359242Z"
               },
               "port" : {
                  "timestamp" : "2017-01-13T16:38:00.543177256Z",
                  "value" : "80"
               },
               "addr" : {
                  "timestamp" : "2017-01-13T16:38:00.543177256Z",
                  "value" : "10.0.0.88"
               },
               "host_node_id" : {
                  "value" : "minikube;<host>",
                  "timestamp" : "2017-01-13T16:37:50.566120599Z"
               },
               "procspied" : {
                  "value" : "true",
                  "timestamp" : "2017-01-13T16:37:50.566263237Z"
               }
            },
            "parents" : {},
            "children" : null,
            "counters" : {},
            "edges" : {}
         },
```

I used the following Kubernetes yaml file to reproduce this:
```
apiVersion: v1
kind: Pod
metadata:
  name: myserver1
  labels:
    name: myserver1
    app: theserver
spec:
  containers:
  - name: myserver1
    image: albanc/toolbox:latest
    args:
      - '/bin/sh'
      - '-c'
      - "/usr/sbin/busybox nc -ll -p 80 -e /bin/cat"
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myserver2
  labels:
    name: myserver2
    app: theserver
spec:
  containers:
  - name: myserver2
    image: albanc/toolbox:latest
    args:
      - '/bin/sh'
      - '-c'
      - "/usr/sbin/busybox nc -ll -p 80 -e /bin/cat"
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: myserver
  name: myserver
spec:
  type: LoadBalancer
  ports:
    - name: app
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: theserver
  clusterIP: 10.0.0.88
---
apiVersion: v1
kind: Pod
metadata:
  name: myclient1
  labels:
    name: myclient1
spec:
  containers:
  - name: myclient1
    image: albanc/toolbox:latest
    args:
      - '/bin/sh'
      - '-c'
      - "(echo FROM client1 ; sleep 6000 ; echo FIN) | /bin/nc 10.0.0.88 80"
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: myclient2
  labels:
    name: myclient2
spec:
  containers:
  - name: myclient2
    image: albanc/toolbox:latest
    args:
      - '/bin/sh'
      - '-c'
      - "(echo FROM client2 ; sleep 6000 ; echo FIN) | /bin/nc 10.0.0.88 80"
    securityContext:
      privileged: true
```

@iaguis was trying a patch that seems to fix this.
