### ISSUE TITLE
k8s: use more restrictive RBAC permissions

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#2149]
We should look into how this may affect Scope. This is to do with 1.6. switching to RBAC. All I know is that GKE will be backwards compatible, and kubeadm might remain backward compatible, but there will be other installation and we will need to investigate the effects of this and document what to do etc, e.g. "Kubernetes The Hard Way" or anything else, like Tectonic might chose the restrictive policy as the default.

**Comment by errordeveloper** [comment]
Essentially I need a list of permissions that Scope requires, like [what we have for Net](https://github.com/weaveworks/weave/blob/8862d4f76e8ccc208d35b05b25f95f465edb7fc6/prog/weave-kube/weave-daemonset-k8s-1.6.yaml).

**Comment by 2opremio** [comment]
@errordeveloper According to our [client code](https://github.com/weaveworks/scope/blob/8c6747f560200accf9a3ad00bcf8ce243741e2b8/probe/kubernetes/client.go) Scope needs:


For viewing:
* list: pods, services, deployments, deplicasets, replicationcontrollers, nodes (and soon daemosets)
* watch: pods

For controls:
* pods: delete, logs
* scales: update

**Comment by omkensey** [comment]
I wrote this to take advantage of the ServiceAccount that's already defined for the Scope agent.  It does seem to work although looking at the list above, it's not complete.  This is an additional two items for the List defined in `scope.yaml`:

```
  - kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: cluster-reader
    rules:
      - apiGroups: [""]
        resources:
          - services
          - nodes
          - replicationcontrollers
          - deployments
          - replicasets
          - pods
        verbs: ["get", "watch", "list"]
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: cluster-reader-global
    subjects:
    - kind: ServiceAccount
      namespace: default
      name: weave-scope
    roleRef:
      kind: ClusterRole
      name: cluster-reader
      apiGroup: rbac.authorization.k8s.io
```

**Comment by rade** [comment]
AFAICT nothing is broken here. `curl https://cloud.weave.works/k8s/v1.6/scope.yaml` returns the following
```
...
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: weave-scope
      labels:
        name: weave-scope
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
      - nonResourceURLs:
          - '*'
        verbs:
          - '*'
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: weave-scope
      labels:
        name: weave-scope
    roleRef:
      kind: ClusterRole
      name: weave-scope
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-scope
        namespace: kube-system
...
```

So I believe the real objective of this issue is to refine the permissions so we don't ask for everything. -> changing summary to match. @errordeveloper if that is incorrect, then please explain what this issue is about.
