### ISSUE TITLE
pod names missing

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#2258]
For some reason I'm seeing this on OpenShift, which reports to be 1.2, but I don't think it is the effective Kubernetes version.

```console
[vagrant@localhost ~]$ oc version 
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
[vagrant@localhost ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0-36-g4a3f9c5", GitCommit:"2e62fab", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0-36-g4a3f9c5", GitCommit:"2e62fab", GitTreeState:"not a git tree"}
[vagrant@localhost ~]$ 
```

![](https://www.dropbox.com/s/ikov29djfgn860x/Screenshot%202017-02-17%2016.36.07.png?dl=1)

This can be reproduced with this simple `Vagrantfile` below and instructions  as documented in #2257.

```Ruby
Vagrant.configure(2) do |config|
  config.vm.box = "thesteve0/openshift-origin"
end
```

You might have to install install the following plugins, but I'm not 100% sure.
```
vagrant plugin install vagrant-registration
vagrant plugin install vagrant-service-manager
```
---

[**Report**](https://gist.github.com/errordeveloper/0f3f29974c0c7c2eb4a9302e3abfeff4/raw/10045366b1818fdf781f9dda793982209dc9d20e/openshift-scope.json)

**Comment by rade** [comment]
> which reports to be 1.2, but I don't think it is the effective Kubernetes version.

*what* makes you think that? I really don't want to spend time investigating this if it turns out it's working fine in a recent k8s.

**Comment by errordeveloper** [comment]
Well, they do have versions of their own, that's one thing. However, I checked and the current OpenShift version number is 3.4. So the 1.2 seen here is the version of origin component, and it's version schema happens to match [Kubernetes one](https://github.com/kubernetes/kubernetes/tags). I will have to check whether this Vagrant box is just behind, or what's the issue OpenShift 3.4 is actually built on Kubernetes 1.2.

**Comment by errordeveloper** [comment]
Also, I really cannot think of any API changes between 1.2 and 1.5 that could cause **_names_** to go away... Could someone take a look at the report at least briefly please? I'm really not familiar enough with contents of the reports, so I don't know what to look out for.

**Comment by errordeveloper** [comment]
I've tested on OpenShift 1.3 and 1.4 just now, and it's broken there.
This is very easy to test actually, they have `oc cluster up` which I didn't know about.
1. [download `oc` (use one of `openshift-origin-client-tools-*`)](https://github.com/openshift/origin/releases/tag/v1.4.1)
2. `oc cluster up --skip-registry-check`
3. `oc login -u system:admin`
4. `oc adm policy add-scc-to-user privileged system:serviceaccount:weave-scope:default`
5. `oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:weave-scope:default`
6. `oc create -f 'https://cloud.weave.works/k8s.yaml?t=<token>'

**Comment by rade** [comment]
The report you posted does not contain any pods. Search for `"topology": "pod"``. Then try the same in, say, our dev instance.

Which begs the question how the UI manages to display anything.

**Comment by errordeveloper** [comment]
Ok, the logs reveal this:
```
time="2017-03-07T12:16:24Z" level=info msg="publishing to: https://cloud.weave.works:443" 
<probe> INFO: 2017/03/07 12:16:24.484750 command line args: --logtostderr=true --mode=probe --no-app=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true --service-token=<elided>
<probe> INFO: 2017/03/07 12:16:24.485191 probe starting, version 1.2.1, ID d4173b8c0e116dd
<probe> INFO: 2017/03/07 12:16:24.578768 kubernetes: targeting api server https://172.30.0.1:443
<probe> ERRO: 2017/03/07 12:16:24.651145 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> ERRO: 2017/03/07 12:16:24.692660 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> INFO: 2017/03/07 12:16:24.763212 Success collecting weave proxy status
<probe> WARN: 2017/03/07 12:16:24.768602 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:24.770875 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused
<probe> INFO: 2017/03/07 12:16:24.771001 Success collecting weave plugin status
<probe> INFO: 2017/03/07 12:16:25.531926 Control connection to cloud.weave.works starting
<probe> WARN: 2017/03/07 12:16:25.846402 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:25.994895 Error collecting weave ps, backing off 20s: exit status 1
<probe> INFO: 2017/03/07 12:16:25.998599 Publish loop for cloud.weave.works starting
<probe> WARN: 2017/03/07 12:16:26.832062 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:27.833311 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:28.793725 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:29.788535 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:30.817688 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:31.857867 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:32.789320 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:33.788070 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:34.782730 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:34.810462 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
<probe> WARN: 2017/03/07 12:16:35.830823 Cannot obtain local pods, reporting all (which may impact performance): Get http://localhost:10255/pods/: dial tcp [::1]:10255: getsockopt: connection refused
```
So looks like we are trying to get pods from kubelet, and kubelet isn't listening on the port or isn't listening on any port, I will look into that.

**Comment by errordeveloper** [comment]
I've looked at the config file (`/var/lib/origin/openshift.local.config/node-192.168.65.2/node-config.yaml`) inside `origin` container:
```yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsDomain: cluster.local
dnsIP: 192.168.65.2
dockerConfig:
  execHandlerName: native
enableUnidling: true
imageConfig:
  format: openshift/origin-${component}:v1.4.1
  latest: false
iptablesSyncPeriod: 30s
kind: NodeConfig
masterClientConnectionOverrides:
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  burst: 40
  contentType: application/vnd.kubernetes.protobuf
  qps: 20
masterKubeConfig: node.kubeconfig
networkConfig:
  mtu: 1450
  networkPluginName: ""
nodeIP: ""
nodeName: 192.168.65.2
podManifestConfig: null
servingInfo:
  bindAddress: 0.0.0.0:10250
  bindNetwork: tcp4
  certFile: server.crt
  clientCA: node-client-ca.crt
  keyFile: server.key
  namedCertificates: null
volumeConfig:
  localQuota:
    perFSGroup: null
volumeDirectory: /var/lib/origin/openshift.local.volumes
```
So it looks like it's listening on `0.0.0.0:10250`...

```
curl -k https://0.0.0.0:10250/pods
Forbidden (reason=User "system:anonymous" cannot get nodes/proxy at the cluster scope, user=system:anonymous, verb=get, namespace=, resource=nodes)
```
And with client cert:
```
# cd /var/lib/origin/openshift.local.config/node-192.168.65.2
# curl -k --cert ./master-client.crt --key ./master-client.key https://0.0.0.0:10250/pods
Forbidden (reason=User "system:node:192.168.65.2" cannot get nodes/proxy at the cluster scope, user=system:node:192.168.65.2, verb=get, namespace=, resource=nodes)
```

I can guess what's the rationale behind talking to `<kubelet>:10255/pods` (i.e. local knowledge is preferred), but I wonder if it's something we can fix with a fallback to API server instead? And, by the way, I heard this API doesn't guarantee to list current pods, it's kind of a cache, so we might want to double check that too.
