### ISSUE TITLE
Add v3 Docker compose launch script to documentation

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2711]
We currently only include version 1 and 2 examples at  https://www.weave.works/docs/scope/latest/installing/#docker-compose

**Comment by Oleg26Dev** [comment]
After 4 years: what about docker-compose file v3 to run Weaver scope?

**Comment by gaby** [comment]
@ZedZipDev @2opremio I was able to run using the same as v2 compose:

```yaml
services:
  scope:
    image: weaveworks/scope:latest
    network_mode: host
    pid: host
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command:
      - "--probe.docker=true"
      - "--weave=false"
```

I can also be run without the `privileged` flag by using:

```yaml
cap_add:
  - NET_ADMIN
  - NET_RAW
```
