### ISSUE TITLE
OpenShift Wrong Kubelet Port

### ISSUE THREAD

**Issue by johnfosborneiii** [weaveworks/scope#3104]
Hi tried running through the install instructions for OpenShift and there were a few issues:
1. I had to modify all the scope.yaml namespace instances to weave-scope instead of weave
2. The agent is hard coded to look for the kubelet on port 10255 when on OpenShift it runs on 10250.

I was able to get past the first issue by manually changing the YAML, but there's no ConfigMap or Env Variable etc to modify what kubelet port the agent tries to use.

**Comment by bboreham** [comment]
Hi, thanks for the report! 

Can you clarify why you needed to change the namespace?  We run all Scope probes in the `weave` namespace in our own clusters, but we don't run OpenShift.

Would you like to make a PR to improve the docs for OpenShift?

If you set `KUBERNETES_NODENAME` it won't bother trying to call kubelet - you can do it in the yaml something like this:

```
    spec:
      containers:
        env:
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
```

This way is more efficient too.
