### ISSUE TITLE
scope: k8s deployment: clusterrole: reducing permissions 

### ISSUE THREAD

**Issue by tasdikrahman** [weaveworks/scope#3153]
the initial yaml borrowed from https://cloud.weave.works/k8s/scope.yaml?k8s-version=1.9.3

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-scope
  labels:
    name: weave-scope
  namespace: weave
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
```

as discussed with @bboreham on slack [here](https://weave-community.slack.com/archives/C985DLV6F/p1523435369000321), we can reduce the number of perms given to it. 

should I add the yaml file with the changes I made to get it work here itself? If yes, please suggest the directory structuring I should follow. I was thinking putting it in 

```
scope/examples/k8s/
```

 Thanks! :)
