### ISSUE TITLE
Basic auth dosn't work if value for user,password from secret

### ISSUE THREAD

**Issue by qurname2** [weaveworks/scope#3590]
Hello!
I find a very strange bug with basic authentification in scope.
I use:
```
docker version: 18.06.1-ce
scope version: try on 1.10.1, 1.10.2
kubectl version: v1.12.3
```
I try to get value for username and password from kubernetes secret, for app and agent, something like this:
```
env:
  - name: ENABLE_BASIC_AUTH
    value: 'true'
  - name: BASIC_AUTH_USERNAME
     valueFrom:
       secretKeyRef:
         name: weave-secret
         key: username
  - name: BASIC_AUTH_PASSWORD
     valueFrom:
       secretKeyRef:
         name: weave-secret
         key: password
```
When attach to the pod, I see env variables
```
$ kubectl -n weave exec -ti weave-scope-app-5b487f6fcd-m8j5k env
ENABLE_BASIC_AUTH=true
BASIC_AUTH_USERNAME=AdmIn
BASIC_AUTH_PASSWORD=12345678
```
For app and agent the env values are the same. But authentication in the browser, I don't pass.
The same effect, if I use command line argument in spec.containers.args for app and agent, like this
```
- '--app.basicAuth=true'
- '--app.basicAuth.username=$(WEAVE_SCOPE_USERNAME)'
- '--app.basicAuth.password=$(WEAVE_SCOPE_PASSWORD)'
```
And again, env variables in the pod exist, but authentification failed.
If I use value for username and password **without kubernetes secret**, all work is fine.
```
- '--app.basicAuth.username=AdmIn'
- '--app.basicAuth.password=12345678'

or if env:

env:
  - name: ENABLE_BASIC_AUTH
     value: 'true'
- name: BASIC_AUTH_USERNAME
  value: 'AdmIn'
- name: BASIC_AUTH_PASSWORD
  value: '12345678'
```

**Comment by bboreham** [comment]
I'm not sure I understand your whole issue, but I can see one problem:

```
- '--app.basicAuth.username=$(WEAVE_SCOPE_USERNAME)'
```

environment variable expansion like `$(XXX)` is done by a shell, and in that context there is no shell, just the Scope process.

**Comment by qurname2** [comment]
I don't think this is a problem, because settings below work perfectly.
In deployment.yaml for app:
```
args:
- '--app.basicAuth=true'
- '--app.basicAuth.username=$(WEAVE_SCOPE_USERNAME)'
- '--app.basicAuth.password=$(WEAVE_SCOPE_PASSWORD)'
env:
- name: WEAVE_SCOPE_USERNAME
  value: 'AdmIn'
- name: WEAVE_SCOPE_PASSWORD
  value: '12345678'
```
And in log app we see:
```
root@master1:# kubectl -n weave logs -f  weave-scope-app-6b7f8b7498-k85rx
<app> INFO: 2019/04/02 11:43:26.514466 app starting, version 1.10.2, ID 1cd568e14de96959
<app> INFO: 2019/04/02 11:43:26.514598 command line args: --app.basicAuth=true --app.basicAuth.password=12345678 --app.basicAuth.username=AdmIn --mode=app
<app> INFO: 2019/04/02 11:43:26.525909 Basic authentication enabled
<app> INFO: 2019/04/02 11:43:26.527100 listening on :4040
...
```
And in daemonset.yaml for agent:
```
args:
- '--probe.basicAuth=true'
- '--probe.basicAuth.username=$(WEAVE_SCOPE_USERNAME)'
- '--probe.basicAuth.password=$(WEAVE_SCOPE_PASSWORD)'
env:
env:
- name: WEAVE_SCOPE_USERNAME
  value: 'AdmIn'
- name: WEAVE_SCOPE_PASSWORD
  value: '12345678'
```
And log for agent:
```
root@master1:# kubectl -n weave logs -f  weave-scope-agent-szsgq
time="2019-04-02T11:49:31Z" level=info msg="publishing to: weave-scope-app:80"
<probe> INFO: 2019/04/02 11:49:31.133555 Basic authentication enabled
<probe> INFO: 2019/04/02 11:49:31.169102 command line args: --mode=probe --probe-only=true --probe.basicAuth=true --probe.basicAuth.password=12345678--probe.basicAuth.username=AdmIn --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true --probe.no-controls=true weave-scope-app:80
<probe> INFO: 2019/04/02 11:49:31.169241 probe starting, version 1.10.2, ID fc2bd4ee1f5c863
...
```

**Comment by qiell** [comment]
Hi @qurname2 
This works for me, please have a look.

Secret:
```
Name:         weave-secret
Namespace:    weave
Labels:       <none>
Annotations:  
Type:         Opaque

Data
====
password:  12 bytes
username:  6 bytes

```

Weave-Scope-App deployment
```
    spec:
      containers:
      - args:
        - --no-probe
        - --app.basicAuth=true
        - --app.basicAuth.username=$(WEAVE_SCOPE_USERNAME)
        - --app.basicAuth.password=$(WEAVE_SCOPE_PASSWORD)
        env:
        - name: WEAVE_SCOPE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: weave-secret
        - name: WEAVE_SCOPE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: weave-secret
```
