### ISSUE TITLE
 error to enable authentication weave-scope-app

### ISSUE THREAD

**Issue by gibati** [weaveworks/scope#3607]
## What happened?

Hi guys, I am trying to activate the basic authentication, but it is not working, after login/password I see on screen the following message.

"nothing to show. This can have any of these reasons:
. We haven't received any reports from probes recently. Are the probes properly connected?
. Containers view only: you're not running DOcker, or you don't have any containers

but if I remove the basicAuth settings, it works perfectly, but unfortunately without authentication

## How to reproduce it?

1. curl "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')" > /tmp/scope.yml
2. kubectl apply -f /tmp/scope.yml
Ref.: https://www.weave.works/docs/scope/latest/installing/#k8s

I am using the following configuration in the /tmp/scope.yml file:
`      
        scope.yml

        metadata:
          labels:
            name: weave-scope-app
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: app
        spec:
          containers:
            - name: app
              args:
                - '--mode=app'
                - '-app.basicAuth'
                - '-app.basicAuth.password=test'
                - '-app.basicAuth.username=test'
                - '-probe.basicAuth'
                - '-probe.basicAuth.password=test'
                - '-probe.basicAuth.username=test'
`

## Versions:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1",  GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", , GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

## Logs:

```
$ kubectl get pods -n weave                                          
NAME                                         READY   STATUS    RESTARTS   AGE
weave-scope-agent-5dgqt                      1/1     Running   0          2h
weave-scope-agent-dfnjh                      1/1     Running   0          2h
weave-scope-agent-pbrwt                      1/1     Running   0          2h
weave-scope-agent-pjwnx                      1/1     Running   0          2h
weave-scope-agent-srk8t                      1/1     Running   0          2h
weave-scope-agent-xfk4r                      1/1     Running   0          2h
weave-scope-app-7976f4b755-h85lx             1/1     Running   0          26m
weave-scope-cluster-agent-554cf5ff98-ft28d   1/1     Running   0          30m

$ kubectl logs -f -n weave weave-scope-app-7976f4b755-h85lx                                                            
<app> INFO: 2019/05/15 18:49:59.050952 app starting, version 1.10.2, ID 5f5362ca4d6fa412
<app> INFO: 2019/05/15 18:49:59.051064 command line args: --app.basicAuth=true --app.basicAuth.password=teste --app.basicAuth.username=teste --mode=app --probe.basicAuth=true --probe.basicAuth.password=teste --probe.basicAuth.username=teste --probe.no-controls=true
<app> INFO: 2019/05/15 18:49:59.055372 Basic authentication enabled
<app> INFO: 2019/05/15 18:49:59.055634 listening on :4040
<app> WARN: 2019/05/15 18:49:59.086436 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<app> WARN: 2019/05/15 18:50:19.100276 Error updating weaveDNS, backing off 40s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.


```

**Comment by satyamz** [comment]
Hi @gibati, 

You have provided wrong configuration in the yaml file. You have provided `Basic Auth` flags only in app container spec. `Basic Auth` flags should be provided with both `app` and `probe` spec.

> "nothing to show. This can have any of these reasons:
. We haven't received any reports from probes recently. Are the probes properly connected?
. Containers view only: you're not running DOcker, or you don't have any containers


Above error is occurring because, you did not specify the basic auth flags in the `probe` container spec. I was able to reproduce this scenario.  

You can refer the following sample yaml. This works for me. 

```yaml

apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: weave
      annotations:
        cloud.weave.works/version: v1.0.0-27-g45f6e64
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/v1.8/scope.yaml",
              "date": "Fri Feb 09 2018 08:45:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope
      namespace: weave
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/v1.8/scope.yaml",
              "date": "Fri Feb 09 2018 08:45:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope
      namespace: weave
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
      - nonResourceURLs:
          - '*'
        verbs:
          - '*'
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/v1.8/scope.yaml",
              "date": "Fri Feb 09 2018 08:45:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope
      namespace: weave
    roleRef:
      kind: ClusterRole
      name: weave-scope
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-scope
        namespace: weave
  - apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/v1.8/scope.yaml",
              "date": "Fri Feb 09 2018 08:45:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      namespace: weave
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      template:
        metadata:
          labels:
            name: weave-scope-app
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: app
        spec:
          containers:
            - name: app
              args:
                - '--no-probe'
                - '--app.basicAuth=true'
                - '--app.basicAuth.password=test'
                - '--app.basicAuth.username=test'

              image: 'satyamz/scope:jobv1'
              imagePullPolicy: Always
              ports:
                - containerPort: 4040
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/v1.8/scope.yaml",
              "date": "Fri Feb 09 2018 08:45:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      namespace: weave
    spec:
      type: NodePort
      ports:
        - name: app
          port: 4040
          protocol: TCP
          nodePort: 32160
      selector:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: weave-scope-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/v1.8/scope.yaml",
              "date": "Fri Feb 09 2018 08:45:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope-agent
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: agent
      namespace: weave
    spec:
      template:
        metadata:
          labels:
            name: weave-scope-agent
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: agent
        spec:
          containers:
            - name: scope-agent
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - '--probe.basicAuth=true'
                - '--probe.basicAuth.password=test'
                - '--probe.basicAuth.username=test'
                - 'weave-scope-app.weave.svc.cluster.local:4040'
              image: 'satyamz/scope:jobv1'
              imagePullPolicy: Always
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: scope-plugins
                  mountPath: /var/run/scope/plugins
                - name: sys-kernel-debug
                  mountPath: /sys/kernel/debug
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          hostPID: true
          serviceAccountName: weave-scope
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
            - name: scope-plugins
              hostPath:
                path: /var/run/scope/plugins
            - name: sys-kernel-debug
              hostPath:
                path: /sys/kernel/debug
      updateStrategy:
        type: RollingUpdate

```
  
Closing this issue as this not an actual issue but a deployment mistake. 

Thanks @gibati for trying out Scope.
