### ISSUE TITLE
"The message port closed before a response was received" when running through Nginx or ALB ingresses

### ISSUE THREAD

**Issue by pavlo** [weaveworks/scope#3652]
Hey!

I've got an EKS cluster and set up the Nginx ingress controller in it. In the cluster there are a  few publicly faced apps exposed via the controller so I assumed it has been set up properly. I then installed weave scope (what an amazing app you guys have written btw!) and played with it via `port-forward` thing and liked it a lot.

Then I decided to expose it to show to colleagues. I created an ingress for the app and that was where troubles began, no matter what I did I saw the "Nothing to show" page in the browser. All I can see in browser console is this:

`Unchecked runtime.lastError: The message port closed before a response was received.`

I assumed it had something to do with web-sockets not being properly handled when the ingress is in use. After a couple of hours of googling and trying this and that I decided to give up with Nginx ingress and setup ALB ingress controller. To my surprise, once it set up, it yielded exactly the same issue and the message in browser's console!

What you guys would recommend to check? Really stuck here... Here's pieces of code I thought would be helpful to show, please let me know if there's anything else I can share to troubleshoot the matter. Thanks!

This is how nginx ingress controller is configured:
```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<here my ARN goes>"

    # Ended up having the following two lines commented out, they did not help 
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http

---
```

This is the app's ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope-app
  namespace: weave
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <my host goes here>
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 29001
```

* Scope version: `1.11.3`
* Kubectl version: `Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-11T03:47:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes version: `1.12`

I omitted ALB ingress setup because I purged it... but I can easily restore it if it would help to get more details, just let me know!

Thanks a lot!
Pavlo
