### ISSUE TITLE
How come I don't get all the purty lines? :p

### ISSUE THREAD

**Issue by YouveGotMeowxy** [weaveworks/scope#3724]
![image](https://user-images.githubusercontent.com/39491297/68421927-d2032400-0164-11ea-8924-c4069a4023c6.png)

I'm using the latest version of Scope via the Docker container on a Win 10 machine w/Docker Desktop.

I thought I was sposed to see a bunch of lines showing how the containers are connected to each other?

Here's the Compose I use:
```
version: '2'

services:
    scope:
        container_name: scope
        hostname: scope
        image: weaveworks/scope
        ports:
            - '9029:4040'
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:rw"
        command:
          - "--probe.docker=true"
          - "--weave=false"
```

Did I screw something up?
