### ISSUE TITLE
How to run Weave Scope in Docker?

### ISSUE THREAD

**Issue by Oleg26Dev** [weaveworks/scope#3887]
My OS is WIndows 10.
That is my docker-compose file
```
version: '3.4'
services:
  scope:
    image: weaveworks/weave:latest
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"

```      
Then run docker-compose:

```
PS D:\WeaveScope> docker-compose up -d
Pulling scope (weaveworks/weave:latest)...
latest: Pulling from weaveworks/weave
21c83c524219: Pull complete
02ec35b6f627: Pull complete
c40f141adde9: Pull complete
a63db11be476: Pull complete
e8d3a1b4fb09: Pull complete
Digest: sha256:a4f1dd7b4fcd3a391c165f1ab20c5f72330c22fe0918c899be67763717bb2a28
Status: Downloaded newer image for weaveworks/weave:latest
Creating weavescope_scope_1 ... done

```But when  I run browser http://localhost:4040 I receive "This site can’t be reached"

What I do wrong?How to fix it?

**Comment by mosoftwareenterprises** [comment]
I am seeing the same issue. I am running Docker on Windows with WSL2. 
#3809 is related/duplicate.

**Comment by mosoftwareenterprises** [comment]
This works for me for Docker on WSL:

```
  scope:
    image: weaveworks/scope:1.13.2
    # network_mode: "host"
    # pid: "host"
    privileged: true
    ports:
      - "0.0.0.0:4040:4040"
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
```

This is a variation of : https://github.com/weaveworks/scope/issues/2842#issuecomment-326636753
